services:

    packerweb:
        restart: on-failure:3
        image: packerweb:latest
        build:
            context: packer/
            dockerfile: packer.Dockerfile
        #devices:
        #    - /dev/kvm
        ports:
          - ${PORT_MASTER:-8080}:8080
        volumes:
          - ./.cache:/root/.cache/packer
          - ./ubuntu:/src
  